# Generated by Django 2.2.4 on 2020-11-27 07:25

import cms.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticfile',
            name='file',
            field=models.FileField(help_text='Please upload static file (image, css, js, etc). This file will be accessible at static/cms/filename', storage=django.core.files.storage.FileSystemStorage(), upload_to=cms.models.get_filename),
        ),
    ]
