# Generated by Django 2.2.4 on 2020-11-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20201127_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
